### ISSUE TITLE
严重-38秒左右固定出现一次断流现象

### ISSUE THREAD

**Issue by liuchengts** [Potterli20/trojan-go-fork#73]
我使用了最新的 trojan-go-fork 版本，数据传输模式是 tcp，发现在v2ray、xray、clash、shadowrocket等客户端下使用，大约38秒左右出现一次断流。

断流场景举例：
1、挂上梯子，在github上下载一个大文件时，固定38秒左右必然出现网络中断。
2、使用 https://chatgpt.com/ 时，几轮对话之后gpt会突然丢失当前连接，提示网络中断。

我目前的替代方案：
使用了原版 trojan-go 最后一个版本，数据模式是tcp，没有这个现象。

**Comment by liuchengts** [comment]
> > 断流时我观察了trojan-go-fork服务端日志，没有任何异常日志。看起来断开是程序的正常处理一样，找不到源头
> 
> 你日记等级是去到那里？

log_level 为 1

**Comment by liuchengts** [comment]
> 不知道是不是我用xray内核有关，而且现在pkg.goole也更新不了xray内核

不清楚，我原来用的是trojan-go 没发生这个情况，trojan-go-fork 只有这个问题，断流的频率非常固定，我是人工计时，大概就是38秒左右，我觉得可能是代码中某个固定行为导致的

**Comment by liuchengts** [comment]
> > > 不知道是不是我用xray内核有关，而且现在pkg.goole也更新不了xray内核
> > 
> > 
> > 不清楚，我原来用的是trojan-go 没发生这个情况，trojan-go-fork 只有这个问题，断流的频率非常固定，我是人工计时，大概就是38秒左右，我觉得可能是代码中某个固定行为导致的
> 
> 我看了相关代码也没有写固定38秒左右，你可以看看ws协议看看，不是套cdn的
> 
> 我感觉是xray的http那边有关的（不准确）

你说的这个情况可能存在，我用的一直是tcp，没有用trojan-go-fork试过ws的方式。等我试试看

**Comment by liuchengts** [comment]
> 主要是我这边pr比较多，动过的东西很少。我自己这边就把v2ray更改为xray，因为trojan-go不支持v2ray v5

这么看来非常有可能在xray那里有点问题。大概3个月前我也从v2ray转到了xray。

流量路径是 shadowrocket -> xray(ss协议) -> trojan-go(当这里是trojan-go-fork时会断流)
流量路径是 shadowrocket -> trojan-go(当这里是trojan-go-fork时会断流)

我觉得你说的ws情况可能是存在的，据我使用xray的情况来看，xray对某些协议支持的并不是很好。也许问题就在那一片，当然这只是猜测，我会试试 trojan-go-fork ws模式验证一下，毕竟 trojan-go-fork 功能更多一些

**Comment by liuchengts** [comment]
> > > 主要是我这边pr比较多，动过的东西很少。我自己这边就把v2ray更改为xray，因为trojan-go不支持v2ray v5
> > 
> > 
> > 这么看来非常有可能在xray那里有点问题。大概3个月前我也从v2ray转到了xray。
> > 流量路径是 shadowrocket -> xray(ss协议) -> trojan-go(当这里是trojan-go-fork时会断流)
> > 流量路径是 shadowrocket -> trojan-go(当这里是trojan-go-fork时会断流)
> > 我觉得你说的ws情况可能是存在的，据我使用xray的情况来看，xray对某些协议支持的并不是很好。也许问题就在那一片，当然这只是猜测，我会试试 trojan-go-fork ws模式验证一下，毕竟 trojan-go-fork 功能更多一些
> 
> 其实我想复活trojan-go的，但没有人进行更新

trojan-go确实是个非常优秀的项目，我其实有些兴趣，因为我用trojan-go和v2ray很多年了。但是我的go水平不太行（只写过几个demo的水平[破涕为笑]），我的主要开发语言不是go

**Comment by liuchengts** [comment]
> > > > > 主要是我这边pr比较多，动过的东西很少。我自己这边就把v2ray更改为xray，因为trojan-go不支持v2ray v5
> > > > 
> > > > 
> > > > 这么看来非常有可能在xray那里有点问题。大概3个月前我也从v2ray转到了xray。
> > > > 流量路径是 shadowrocket -> xray(ss协议) -> trojan-go(当这里是trojan-go-fork时会断流)
> > > > 流量路径是 shadowrocket -> trojan-go(当这里是trojan-go-fork时会断流)
> > > > 我觉得你说的ws情况可能是存在的，据我使用xray的情况来看，xray对某些协议支持的并不是很好。也许问题就在那一片，当然这只是猜测，我会试试 trojan-go-fork ws模式验证一下，毕竟 trojan-go-fork 功能更多一些
> > > 
> > > 
> > > 其实我想复活trojan-go的，但没有人进行更新
> > 
> > 
> > trojan-go确实是个非常优秀的项目，我其实有些兴趣，因为我用trojan-go和v2ray很多年了。但是我的go水平不太行（只写过几个demo的水平[破涕为笑]），我的主要开发语言不是go
> 
> 查gpt😂，我都是这样的

哈哈哈，这确实是个好办法。这个项目和方向确实需要一些感兴趣的人来维护，长期不更新可能过几年之后就彻底被识别了。我没搞清楚为什么trojan-go作者放弃维护它了，看起来并不是被喝茶了，不然代码库应该被删除了

**Comment by liuchengts** [comment]
最新发现 使用 trojan-go-fork（版本为 V2024.08.04 ） ，ws+tls +cf 模式 也会出现断流

**Comment by liuchengts** [comment]
> > 最新发现 使用 trojan-go-fork（版本为 V2024.08.04 ） ，ws+tls +cf 模式 也会出现断流
> 
> 7月28号，有没有问题？
> 我看到我那边有个7月30号修改的，不知道有没有影响![Screenshot_2024-10-24-14-47-30-848_com.github.android.jpg](https://github.com/user-attachments/assets/089bcf57-cb55-440b-9676-163d44cf1d50)
> 
> ![Screenshot_2024-10-24-14-47-26-729_com.github.android.jpg](https://github.com/user-attachments/assets/6654357d-fac8-49dc-8f1d-7d9d77d5da12)
> 
> 

嗯，晚点我试试这个版本

我用目前最新版本xray，入站为trojan tcp+tls（不用xray特有的功能）模式测试，没有断流

**Comment by so1ar** [comment]
作者你好，我最近也遇到了类似的 bug，服务端用docker部署的，用的是 tcp 模式，客户端用的 Clash Meta 内核，根据我的手动计时差不多正好30秒断流一次。

换成原版的 p4gefau1t/trojan-go 镜像就没有再遇到断流了，另外我还测试了 teddysun/trojan-go 这个镜像，根据他的[描述](https://hub.docker.com/r/teddysun/trojan-go)也是用的trojan-go-fork这个项目的代码，不过是2023.11.18版本的，也没有遇到断流的情况。

**Comment by so1ar** [comment]
> > 作者你好，我最近也遇到了类似的 bug，服务端用docker部署的，用的是 tcp 模式，客户端用的 Clash Meta 内核，根据我的手动计时差不多正好30秒断流一次。
> > 换成原版的 p4gefau1t/trojan-go 镜像就没有再遇到断流了，另外我还测试了 teddysun/trojan-go 这个镜像，根据他的[描述](https://hub.docker.com/r/teddysun/trojan-go)也是用的trojan-go-fork这个项目的代码，不过是2023.11.18版本的，也没有遇到断流的情况。
> 
> 最新的版本还是会？

是的，最新版本 V2025.03.09，我试了还是会断流。

我刚刚用二分法测试了 dockerhub 上 trojan-go-fork 的镜像版本，发现最后一个不会断流的版本是 V2023.12.24，从 V2023.12.31 开始都会断流。

另外我还发现 V2023.11.26 到 V2023.12.17 版本的trojan-go-fork，我用 Clash Meta 会连接失败，服务端日志是这样的：

```
[INFO]  2025/03/11 15:21:03 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:03 empty tls fallback port
[WARN]  2025/03/11 15:21:03 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 42 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc000012530?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc00031c120)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc00003a480})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 5
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
[INFO]  2025/03/11 15:21:07 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:07 empty tls fallback port
[WARN]  2025/03/11 15:21:07 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 41 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc0002b5120?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc0002da120)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc00029b3c0})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 19
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
[INFO]  2025/03/11 15:21:08 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:08 empty tls fallback port
[WARN]  2025/03/11 15:21:08 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 28 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc000269200?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc00026e360)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc00024f300})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 5
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
[INFO]  2025/03/11 15:21:09 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:09 empty tls fallback port
[WARN]  2025/03/11 15:21:09 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 39 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc00026ae60?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc000272360)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc00024f470})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 5
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
[INFO]  2025/03/11 15:21:10 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:10 empty tls fallback port
[WARN]  2025/03/11 15:21:10 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 39 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc00027b240?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc000136240)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc0002614b0})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 5
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
[INFO]  2025/03/11 15:21:13 trojan-go V2023.12.17 initializing
[WARN]  2025/03/11 15:21:13 empty tls fallback port
[WARN]  2025/03/11 15:21:13 empty tls http response
panic: interface conversion: net.Conn is *transport.Conn, not *websocket.InboundConn
                                                                                                                                                                                                
goroutine 27 [running]:
github.com/Potterli20/trojan-go-fork/tunnel/trojan.GetRealIP(0xc00026b1f0?)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:71 +0x171
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Auth(0xc0002901b0)
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:99 +0x247
github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1({0x10694b8?, 0xc00024f2e0})
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:178 +0x1d1
created by github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop in goroutine 5
        github.com/Potterli20/trojan-go-fork/tunnel/trojan/server.go:168 +0xf6
```

**Comment by liuchengts** [comment]
出现这个问题之后我转用了xray的标准trojan-go。没有出现断流。可以尝试升级trojan-go-fork的xray内核试试，有可能是xray某些版本引起的

**Comment by so1ar** [comment]
> 试一下这个docker pull ghcr.io/potterli20/trojan-go-fork:snapshot

刚试了这个版本还是会断流。

**Comment by so1ar** [comment]
> > > 试一下这个docker pull ghcr.io/potterli20/trojan-go-fork:snapshot
> > 
> > 
> > 刚试了这个版本还是会断流。
> 
> 有没有相关日记？

我刚试了下把 loglevel 设成 0，下面是断流时产生的日志：
```
[INFO]  2025/03/13 16:32:22 trojan-go d297136 initializing
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel.NewAddressFromHostPort:metadata.go:138 network type : tcp HOST: 0.0.0.0
[WARN]  2025/03/13 16:32:22 empty tls fallback port
[WARN]  2025/03/13 16:32:22 empty tls http response
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/tls.NewServer:server.go:373 tls server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/trojan.NewServer:server.go:269 auth by config file
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/statistic/memory.NewAuthenticator:memory.go:389 memory authenticator created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel.NewAddressFromHostPort:metadata.go:138 network type : tcp HOST: filebrowser
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/trojan.NewServer:server.go:307 trojan server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/mux.NewServer:server.go:92 mux server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/simplesocks.NewServer:server.go:95 simplesocks server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/websocket.NewServer:server.go:168 websocket server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel.NewAddressFromHostPort:metadata.go:138 network type : tcp HOST: filebrowser
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel.NewAddressFromHostPort:metadata.go:138 network type : tcp HOST: filebrowser
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/trojan.NewServer:server.go:307 trojan server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/mux.NewServer:server.go:92 mux server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/simplesocks.NewServer:server.go:95 simplesocks server created
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel.NewAddressFromHostPort:metadata.go:138 network type : tcp HOST:
[DEBUG] 2025/03/13 16:32:22 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).AcceptConn:server.go:187 next proto http
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:55232
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:55232
[TRACE] 2025/03/13 16:32:27 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:55232 tunneling to push.services.mozilla.com:443
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:55248
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:55248
[TRACE] 2025/03/13 16:32:27 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:27 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:55248 tunneling to push.services.mozilla.com:443
[DEBUG] 2025/03/13 16:32:28 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:55836
[DEBUG] 2025/03/13 16:32:28 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:55836
[TRACE] 2025/03/13 16:32:28 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:28 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:28 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:55836 tunneling to alive.github.com:443
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:55850
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:55850
[TRACE] 2025/03/13 16:32:31 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:55850 tunneling to www.gstatic.com:443
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:102 conn relay ends
[DEBUG] 2025/03/13 16:32:31 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:55850 tunneling to www.gstatic.com:443 closed sent: 2.96 KiB recv: 463 B
[DEBUG] 2025/03/13 16:32:32 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:55852
[DEBUG] 2025/03/13 16:32:32 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:55852
[TRACE] 2025/03/13 16:32:32 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:32 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:32 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:55852 tunneling to sync-1-us-west1-g.sync.services.mozilla.com:443
[DEBUG] 2025/03/13 16:32:38 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:59940
[DEBUG] 2025/03/13 16:32:38 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:59940
[TRACE] 2025/03/13 16:32:38 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:38 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:38 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:59940 tunneling to github.com:443
[DEBUG] 2025/03/13 16:32:39 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:59956
[DEBUG] 2025/03/13 16:32:39 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:59956
[TRACE] 2025/03/13 16:32:39 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:32:39 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:32:39 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:59956 tunneling to objects.githubusercontent.com:443
[DEBUG] 2025/03/13 16:32:40 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:102 conn relay ends
[DEBUG] 2025/03/13 16:32:40 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:59940 tunneling to github.com:443 closed sent: 7.96 KiB recv: 808 B
[DEBUG] 2025/03/13 16:32:57 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:99 timeout conn relay
[DEBUG] 2025/03/13 16:32:57 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:55232 tunneling to push.services.mozilla.com:443 closed sent: 861 B recv: 1.44 KiB
[DEBUG] 2025/03/13 16:32:57 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:99 timeout conn relay
[DEBUG] 2025/03/13 16:32:57 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:55248 tunneling to push.services.mozilla.com:443 closed sent: 1.16 KiB recv: 2.13 KiB
[DEBUG] 2025/03/13 16:32:58 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:99 timeout conn relay
[DEBUG] 2025/03/13 16:32:58 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:55836 tunneling to alive.github.com:443 closed sent: 4.19 KiB recv: 2.81 KiB
[DEBUG] 2025/03/13 16:33:00 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:44378
[DEBUG] 2025/03/13 16:33:00 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:44378
[TRACE] 2025/03/13 16:33:00 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:33:00 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:33:00 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:44378 tunneling to alive.github.com:443
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:99 timeout conn relay
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:55852 tunneling to sync-1-us-west1-g.sync.services.mozilla.com:443 closed sent: 1.39 KiB recv: 4.50 KiB
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:44394
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:44394
[TRACE] 2025/03/13 16:33:02 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:33:02 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:44394 tunneling to push.services.mozilla.com:443
[DEBUG] 2025/03/13 16:33:03 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:44406
[DEBUG] 2025/03/13 16:33:03 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:44406
[TRACE] 2025/03/13 16:33:03 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:33:03 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:33:03 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:44406 tunneling to push.services.mozilla.com:443
[DEBUG] 2025/03/13 16:33:09 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:99 timeout conn relay
[DEBUG] 2025/03/13 16:33:09 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:59956 tunneling to objects.githubusercontent.com:443 closed sent: 309.49 MiB recv: 1.21 KiB
[DEBUG] 2025/03/13 16:33:11 github.com/Potterli20/trojan-go-fork/tunnel/transport.(*Server).acceptLoop.func1:server.go:55 tcp connection from 172.25.0.5:52264
[DEBUG] 2025/03/13 16:33:11 github.com/Potterli20/trojan-go-fork/tunnel/tls.(*Server).acceptLoop.func1:server.go:148 tls connection from 172.25.0.5:52264
[TRACE] 2025/03/13 16:33:11 tls handshake TLS_AES_128_GCM_SHA256 false http/1.1
[DEBUG] 2025/03/13 16:33:11 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*Server).acceptLoop.func1:server.go:212 normal trojan connection
[DEBUG] 2025/03/13 16:33:11 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Record:server.go:145 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 from 172.25.0.5:52264 tunneling to objects.githubusercontent.com:443
[DEBUG] 2025/03/13 16:33:12 github.com/Potterli20/trojan-go-fork/proxy.(*Proxy).relayConnLoop.func2.1:proxy.go:102 conn relay ends
[DEBUG] 2025/03/13 16:33:12 github.com/Potterli20/trojan-go-fork/tunnel/trojan.(*InboundConn).Close:server.go:65 user 9a364fd8f4854e81abf10624c199a21dc97cee49bbbafcfb5f739d89 KeyShare    RealIP 172.25.0.5 from 172.25.0.5:52264 tunneling to objects.githubusercontent.com:443 closed sent: 5.77 KiB recv: 1.23 KiB
```
这个 torjan-go 服务器是运行在反向代理后面的，那个 172.25.0.5 是反代服务器的 ip，不过我试过就算不用反代也一样会断流。

另外我刚发现 sing-box 也有一个 trojan 服务器的[实现](https://sing-box.sagernet.org/zh/manual/proxy-protocol/trojan/#server-example)，试了下也不会断流，暂时先用 sing-box 了。
